* How hard can it be to roll my own note taking system?
:PROPERTIES:
:CUSTOM_ID: how-hard-can-it-be-to-roll-my-own-note-taking-system
:END:
I like to build the tools I use. I also like my website,
[[https://play.teod.eu/][play.teod.eu]].

In a sense, my website is my note taking system. But there are gaps.

1. I can only work with my website from a computer with Emacs, Pandoc,
   Git, Make, Clojure and Babashka
2. The UX for tagging pages is poor
3. The UX for "capturing notes" is poor.

I don't think I'll "just fix all of these by writing some code". But I'd
like to at least try to address some of these concerns.

** Deploying to application.garden
:PROPERTIES:
:CUSTOM_ID: deploying-to-application.garden
:END:
I want to try use [[https://application.garden/][application.garden]]
for something. Why? It seems to handle the impure parts of application
deployment in a neater way than I've seen elsewhere. Let's figure out if
that assumption is correct in practice.

** Multi-user data model
:PROPERTIES:
:CUSTOM_ID: multi-user-data-model
:END:

Rough idea:

1. lean on garden's login system
2. store notes on disk (text files by uuid under user id)

Operations:

1. List my notes
2. Edit a note
3. Save changes
4. Create a new note

"multi-editing and groups?" Let's not start there. =garden groups= looks
interesting, but let's not make this too hard on ourselves.

** Storage quotas
:PROPERTIES:
:CUSTOM_ID: storage-quotas
:END:
Current quotas seem to be:

1. Max 10 GB per user
2. Max 10 projects per user

(That should be plenty for my use case)

Here's my current usage:

#+begin_src sh
$ garden list
#+end_src

| name          | status  | git-rev | url                               | deployed-at                    | deployed-by |
|---------------+---------+---------+-----------------------------------+--------------------------------+-------------|
| garden-teodor | running | 1097d72 | https://garden-teodor.apps.garden | April 12, 2024 at 4:06:54 PM Z | teodorlu    |

Running projects limit: 1/10 Used storage quota: 0MB/10GB (0.0%)
