* Capture notes for weeknotes
"What's weeknotes?" you say?
Consider reading https://doingweeknotes.com/.

When Friday has come and you sit down to write weeknotes, where to you start out?
With a blank page?
Or did you have the foresight to take some notes during the week?

=weeknotes-notes= is built to let you take notes in order to write weeknotes.

It's up: https://weeknotes-notes.apps.garden/

But there's no user isolation, so:

1. Don't write things you don't want to be public forever
2. Please don't abuse it :)
* 2024-04-13
** How hard can it be to roll my own note taking system?

I like to build the tools I use. I also like my website,
[[https://play.teod.eu/][play.teod.eu]].

In a sense, my website is my note taking system. But there are gaps.

1. I can only work with my website from a computer with Emacs, Pandoc,
   Git, Make, Clojure and Babashka
2. The UX for tagging pages is poor
3. The UX for "capturing notes" is poor.

I don't think I'll "just fix all of these by writing some code". But I'd
like to at least try to address some of these concerns.

** Deploying to application.garden
:PROPERTIES:
:CUSTOM_ID: deploying-to-application.garden
:END:
I want to try use [[https://application.garden/][application.garden]]
for something. Why? It seems to handle the impure parts of application
deployment in a neater way than I've seen elsewhere. Let's figure out if
that assumption is correct in practice.

** Multi-user data model
:PROPERTIES:
:CUSTOM_ID: multi-user-data-model
:END:

Rough idea:

1. lean on garden's login system
2. store notes on disk (text files by uuid under user id)

Operations:

1. List my notes
2. Edit a note
3. Save changes
4. Create a new note

"multi-editing and groups?" Let's not start there. =garden groups= looks
interesting, but let's not make this too hard on ourselves.

** Storage quotas
:PROPERTIES:
:CUSTOM_ID: storage-quotas
:END:

Current quotas seem to be:

1. Max 10 GB per user
2. Max 10 projects per user

(That should be plenty for my use case)

Here's my current usage:

#+begin_src sh
$ garden list
#+end_src

| name          | status  | git-rev | url                               | deployed-at                    | deployed-by |
|---------------+---------+---------+-----------------------------------+--------------------------------+-------------|
| garden-teodor | running | 1097d72 | https://garden-teodor.apps.garden | April 12, 2024 at 4:06:54 PM Z | teodorlu    |

Running projects limit: 1/10 Used storage quota: 0MB/10GB (0.0%)
** Garden templates

There are templates for garden:

| default template | https://github.com/nextjournal/garden-template       |
| Clerk template   | https://github.com/nextjournal/garden-template-clerk |

Per 2024-04-13, I've tried the default template.
It spits out an httpkit application that demonstrates most/all of garden's features.
I haven't tried the Clerk template.
* 2024-04-14
** I Know What To Do!
I Will Create A Note System Specifically For Writing Weeknotes!!!!

:grin:

this is perfect!

1. It's what I need
2. It's narrow

Perfect!
** Should I spend today writing code for writing weeknotes or writing weeknotes?
Perhaps bias towards doing, so perhaps do for most of the time, then timebox some time for the weeknotes.

I /should publish/ weeknotes today.
Consistency is king!
* 2024-04-21
** 08:52 What to do?
1. Open the app in production
2. Fix problems that I can see!

This fills me with encouragement rather than a fear that it's all too big.
** 08:54 What do do, alternative 2?
1. Try to use it for my goal (writing weeknotes)
2. See where it fails first.

Let's just do it.
I now have a list of UUIDs.
That's not enough!
I need to read each.
Let's make that happen.
